name: mlpython
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - jupyterlab
  - scipy
  - h5py
  - tensorflow=2
  - keras
  - pytorch
  - pillow
  - hyperopt
  - pandoc
  - nbconvert[qtpdf]
